name: "infra-gitops"

on:
  push:
    branches:
      - iac-gitops
    paths:  
      - terraform/**
      - .github/workflows/**
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  S3_BUCKET: ${{ secrets.S3_BUCKET }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  EKS_CLUSTER: ${{ vars.EKS_CLUSTER }}

jobs:
  terraform:
    name: Terraform Security and Linting
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: |
          terraform init
          # Optionally uncomment and configure if using remote backend:
          # terraform init -backend-config="bucket=${S3_BUCKET}" -backend-config="region=${AWS_REGION}"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Format Check with Diff
        run: terraform fmt -check -diff -recursive

      - name: Run TFLint
        uses: reviewdog/action-tflint@v1
        with:
          reporter: github-pr-review
          filter_mode: file
          working_directory: terraform


      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          soft_fail: false
          working_directory: terraform

      - name: Generate Terraform Plan
        id: plan
        run: |
          terraform plan -out=tfplan.binary
          terraform show -json tfplan.binary > tfplan.json

      - name: Set up Infracost
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Generate Infracost breakdown
        run: |
          infracost breakdown \
            --path=. \
            --terraform-plan-flags="-out=tfplan.binary" \
            --format=json \
            --out-file=infracost.json

      - name: Upload Infracost JSON
        uses: actions/upload-artifact@v4
        with:
          name: infracost
          path: terraform/infracost.json

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: terraform/tfplan.binary

      - name: Upload Terraform Plan JSON
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-json
          path: terraform/tfplan.json

      
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan.binary

  destroy:
    name: "Destroy Infra on AWS"
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    defaults:
      run:
        shell: bash
        working-directory: ./terraform
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: terraform init -backend-config="bucket=$S3_BUCKET"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get Kubernetes config
        run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER }} --region ${{ env.AWS_REGION }} 

      - name: Delete Ingress controller
        run: kubectl delete -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.12.0-beta.0/deploy/static/provider/aws/deploy.yaml

      - name: Empty ECR Repository
        run: |
          REPOSITORY_NAME=${{ vars.ECR_REPO }}
          IMAGES=$(aws ecr list-images --repository-name $REPOSITORY_NAME --query 'imageIds[*]' --output json)
          if [[ "$IMAGES" != "[]" ]]; then
            echo "Deleting images from $REPOSITORY_NAME..."
            aws ecr batch-delete-image --repository-name $REPOSITORY_NAME --image-ids "$IMAGES"
          else
            echo "No images found in $REPOSITORY_NAME."
          fi

      - name: Terraform destroy
        run: terraform destroy -auto-approve -input=false
